### PR TITLE
Haile/create dashboard screen

### PR DESCRIPTION
**Pull request by hello-world-was-taken**

### CODE REVIEW

**Comment by hello-world-was-taken** [comment]
[Implement field card](https://trello.com/c/iOZQ3TPD/18-implement-field-card)

**Comment by hello-world-was-taken** [comment]
[Implement alert card](https://trello.com/c/pdPZkvFi/19-implement-alert-card)

**Comment by hello-world-was-taken** [comment]
[setup background drawables](https://trello.com/c/AAAABiX4/20-setup-background-drawables)

**Review by nawrazi — APPROVED** [review]

**Comment by hello-world-was-taken** [comment]
[Setup UI for home screen](https://trello.com/c/8qYsnszP/2-setup-ui-for-home-screen)

**Pull request merged**
