### PR TITLE
Haile/setup graph service

### PR DESCRIPTION
**Pull request by hello-world-was-taken**

### CODE REVIEW

**Comment by hello-world-was-taken** [comment]
[Integrate wind graph](https://trello.com/c/7M7VIZJ5/71-integrate-wind-graph)

**Comment by nawrazi** [comment]
[Integrate snow depth graph](https://trello.com/c/P9WvUxP8/70-integrate-snow-depth-graph)

**Comment by nawrazi** [comment]
[Integrate preciptation graph](https://trello.com/c/f3MhPy0R/69-integrate-preciptation-graph)

**Comment by nawrazi** [comment]
[Integrate temperature graph](https://trello.com/c/HEZk8aYk/68-integrate-temperature-graph)

**Pull request merged**
